Write-Host "🚀 Instalando MCP DevSecOps no Windows (instruções básicas)"
Write-Host "1) Instale Docker Desktop via https://www.docker.com/get-started"
Write-Host "2) Instale Python 3.10+ e adicione ao PATH"
Write-Host "3) Abra PowerShell (Admin) e execute:"
Write-Host "   python -m pip install --upgrade pip"
Write-Host "   python -m pip install langchain chromadb PyPDF2 requests openai bandit"
Write-Host "4) Instale Ollama se desejar (https://ollama.com/download)"
Write-Host "5) Baixe imagens docker: sonarqube, owasp/zap2docker-stable, aquasec/trivy, prom/prometheus, grafana/grafana"
Write-Host "Instalação manual concluída. Leia README.md para detalhes."
